name: Comment gid

on:
  workflow_dispatch:
  issues:
    types: [
      opened,
      edited,
      deleted,
      closed,
      reopened,
      labeled,
      unlabeled,
    ]

jobs:
  grasp_issue:
    runs-on: ubuntu-latest
    name: Grasp issue dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: gameagelayer/gid@main
        with:
          label: 'root'
          github_token: ${{secrets.GITHUB_TOKEN}}
